 /* CREAR ESTAS DOS TABLAS*/
  
CREATE TABLE actor (
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(70),
PRIMARY KEY(id)
);


CREATE TABLE actor_pelicula (
id INT NOT NULL AUTO_INCREMENT,
actor_id INT NOT NULL,
pelicula_id INT NOT NULL,
PRIMARY KEY(id)
);

/* INSERTAR SCRIPT-PASO-3 ACTOR_PELICULA Y ACTOR*/